#!/bin/bash
set -u -e -C
shopt -s failglob

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }

function ask_yN {
    local answer=''
    read -n 1 -s -p $'\e[34m'"$* [yN]"$'\e[m' answer
    if test "${answer}" = y; then
        info yes
        return 0
    fi
    info no
    return 1
}


name="${1?need file of dependencies}"
mapfile -t depends < "${name}"

version="$(stat -c%Y "${name}")"
release="$(date +%s)"

tmp="$(mktemp -t -d "${name}.XXXXXXXX")"

echo "Temporary directory: ${tmp}"

cat <<. > "${tmp}/PKGBUILD"
pkgname='metapkg_${name}'
pkgver=${version}
pkgrel=${release}
arch=(any)
pkgdesc='Metapackage only to hold dependencies'

package() {
    depends=( $(printf '%q\n' "${depends[@]}") )
}
.

env -C "${tmp}" makepkg -c PKGDEST=/tmp/metapkg/

echo "Removing temporary directory: ${tmp}"
rm -rf "${tmp}"

find /tmp/metapkg/ -type f | sort 

